### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(OriginUi_calculator)
add_subdirectory(OriginUi_calculatorContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    OriginUi_calculatorplugin
    OriginUi_calculatorContentplugin
    QtQuickDesignerComponents)