### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(infinityOS_calculator)
add_subdirectory(infinityOS_calculatorContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    infinityOS_calculatorplugin
    infinityOS_calculatorContentplugin
    QtQuickDesignerComponents)